name: contextos-ejercicio1

on:
    push:


jobs:
    github-envs-into-steps:
        runs-on: ubuntu-latest
        steps:
            - name: Set env variable
              run: echo "APP_NAME=my-app" >> "$GITHUB_ENV"

            - name: use variable
              run: echo "Application $APP_NAME"

            - name: use variable in another step
              run: echo "Running application $APP_NAME"
