name: Frontend CI contextos

on:
    push:

jobs:
    ci:
        uses: ./.github/workflows/contextos-ejercicio7-reutilizable.yml
        with:
            node-version: '22'
            enviroment: 'development'