name: ejercicio3 - include

on:
  push:

jobs:
  install-dependencies:
    strategy:
      matrix:
        node: [20, 22]

        include:
          - node: 24

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
